### ISSUE TITLE
Getting Error while predicting

### ISSUE THREAD

**Issue by allhelllooz** [YongWookHa/im2latex#3]
Hi, I am trying to predict with epoch-1 model which I was able to train.
I am getting  error at these lines. During training I got no issue.
Can you plz help me resolve this. So that I can continue further epochs & evaluate the model.

            out = self.model(images)  # [B, max_len, vocab_size]
            print("==> var out type - ", type(out))
            print("==> var out shape - ", out.shape)
            out = out.argmax(2)

ERROR
```
INFO]: Program will run on *****GPU-CUDA***** 
[INFO]: Loading checkpoint 'experiments/im2latex-un/checkpoints/best.pt'
[INFO]: Checkpoint loaded successfully from 'experiments/im2latex-un/checkpoints/best.pt' at (epoch 2) at (iteration 10332)

0 : data/test_imgs/part32_13321_mathit_213.210.174.png
1 : data/test_imgs/part17_12520_mathsf.png
==> var out type - <class 'torch.Tensor'>
==> var out shape - torch.Size([2, 129])
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    main()
  File "main.py", line 32, in main
    agent.run()
  File "/home/im2latex/agents/im2latex.py", line 165, in run
    self.predict()
  File "/home/im2latex/agents/im2latex.py", line 292, in predict
    out = out.argmax(2)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
```

**Comment by YongWookHa** [comment]
Hello,

https://github.com/YongWookHa/im2latex/blob/e69170073e2e49d88607980cd31852b32f47e6f3/agents/im2latex.py#L289

comment out the line then you can proper output.

**Comment by allhelllooz** [comment]
Cool working now. Thanks for quick reply !!
